import { Link } from 'react-router-dom'

export default function Landing() {
  return (
    <div>
      {/* HERO */}
      <section className="max-w-6xl mx-auto px-6 pt-20 pb-24 grid md:grid-cols-2 gap-12 items-center">
        <div>
          <p className="font-mono text-xs text-accent tracking-widest uppercase mb-4">Built for Year 11 &amp; 12</p>
          <h1 className="font-display text-5xl md:text-6xl font-bold text-white leading-[1.05] tracking-tight">
            Stop wondering<br />what to study.
          </h1>
          <p className="mt-6 text-lg text-muted max-w-md">
            Upload assessment notifications and StudentSync turns them into a personalised, week-by-week action plan — so you always know the next right move.
          </p>
          <div className="mt-8 flex items-center gap-4">
            <Link to="/register" className="bg-accent text-ink font-medium px-6 py-3 rounded-lg hover:bg-accent/90 transition">
              Get started
            </Link>
            <Link to="/dashboard" className="border border-line text-slate-200 px-6 py-3 rounded-lg hover:border-accent/40 transition flex items-center gap-2">
              <i className="ti ti-player-play text-sm"></i> View demo
            </Link>
          </div>
        </div>
        <div className="relative">
          <div className="absolute -inset-4 bg-accent2/10 rounded-3xl blur-3xl"></div>
          <div className="relative bg-panel border border-line rounded-2xl p-6 shadow-[0_0_0_1px_rgba(122,246,199,0.15),0_0_40px_-10px_rgba(122,246,199,0.35)]">
            <div className="flex items-center justify-between mb-5">
              <p className="font-display font-bold text-white">Economics — Federal Budget Essay</p>
              <span className="font-mono text-xs text-accent bg-accent/10 px-2 py-1 rounded">3 days left</span>
            </div>
            <div className="space-y-3">
              <div className="flex items-center gap-3 text-sm">
                <i className="ti ti-circle-check text-accent"></i><span className="text-muted line-through">Read task &amp; rubric</span>
              </div>
              <div className="flex items-center gap-3 text-sm">
                <i className="ti ti-circle-check text-accent"></i><span className="text-muted line-through">Build TEEL essay outline</span>
              </div>
              <div className="flex items-center gap-3 text-sm">
                <i className="ti ti-circle-dashed text-slate-500"></i><span className="text-slate-200">Draft body paragraphs</span>
              </div>
              <div className="flex items-center gap-3 text-sm">
                <i className="ti ti-circle-dashed text-slate-500"></i><span className="text-slate-200">Final review &amp; submit</span>
              </div>
            </div>
            <div className="mt-6 pt-5 border-t border-line flex items-center justify-between">
              <span className="text-xs text-muted">Generated by StudentSync AI</span>
              <span className="font-mono text-xs text-accent2">62% complete</span>
            </div>
          </div>
        </div>
      </section>

      {/* FEATURES */}
      <section className="max-w-6xl mx-auto px-6 py-20 border-t border-line">
        <p className="font-mono text-xs text-accent2 tracking-widest uppercase mb-3">How it works</p>
        <h2 className="font-display text-3xl font-bold text-white mb-12">Four tools, one rhythm.</h2>
        <div className="grid md:grid-cols-4 gap-6">
          <FeatureCard icon="ti-upload" title="Smart assessment upload" desc="Drop in a photo, PDF, or screenshot of any task sheet and StudentSync reads the subject, due date, weighting and requirements." />
          <FeatureCard icon="ti-route" title="AI study planning" desc="Every assessment is broken into a realistic week-by-week plan, fitted around everything else already on your plate." />
          <FeatureCard icon="ti-layout-dashboard" title="Productivity dashboard" desc="One screen for today's tasks, study sessions, and what's coming up — no more checking five different apps." />
          <FeatureCard icon="ti-chart-line" title="Progress tracking" desc="Completion rates, weekly study hours, and streaks — so momentum is visible, not just felt." />
        </div>
      </section>

      {/* AI BOUNDARY */}
      <section className="max-w-6xl mx-auto px-6 py-4">
        <div className="bg-panel border border-accent2/30 rounded-xl p-5 flex items-start gap-4">
          <i className="ti ti-shield-check text-accent2 text-2xl mt-1"></i>
          <div>
            <h3 className="font-display font-bold text-white mb-1">Planning, not answers</h3>
            <p className="text-sm text-muted">StudentSync's AI organises your time and breaks down tasks — it never writes assignment content for you. It's built to help you do the work, not skip it.</p>
          </div>
        </div>
      </section>

      {/* PRICING */}
      <section className="max-w-6xl mx-auto px-6 py-20 border-t border-line">
        <p className="font-mono text-xs text-accent2 tracking-widest uppercase mb-3">Pricing</p>
        <h2 className="font-display text-3xl font-bold text-white mb-12">Free to start. Always.</h2>
        <div className="grid md:grid-cols-3 gap-6">
          <div className="bg-panel border border-line rounded-xl p-6">
            <h3 className="font-display font-bold text-white mb-1">Free</h3>
            <p className="font-display text-3xl font-bold text-white mb-4">$0</p>
            <ul className="text-sm text-muted space-y-2 mb-6">
              <li className="flex gap-2"><i className="ti ti-check text-accent mt-0.5"></i>Unlimited assessments</li>
              <li className="flex gap-2"><i className="ti ti-check text-accent mt-0.5"></i>AI study plans</li>
              <li className="flex gap-2"><i className="ti ti-check text-accent mt-0.5"></i>Focus timer &amp; streaks</li>
            </ul>
            <Link to="/register" className="w-full block text-center border border-line rounded-lg py-2 text-sm hover:border-accent/40 transition">Get started</Link>
          </div>
          <div className="bg-panel border-2 border-accent rounded-xl p-6 relative">
            <span className="absolute -top-3 left-6 bg-accent text-ink text-xs font-medium px-3 py-1 rounded-full">Most popular</span>
            <h3 className="font-display font-bold text-white mb-1">Plus</h3>
            <p className="font-display text-3xl font-bold text-white mb-4">$4<span className="text-sm text-muted font-body">/mo</span></p>
            <ul className="text-sm text-muted space-y-2 mb-6">
              <li className="flex gap-2"><i className="ti ti-check text-accent mt-0.5"></i>Everything in Free</li>
              <li className="flex gap-2"><i className="ti ti-check text-accent mt-0.5"></i>Calendar sync</li>
              <li className="flex gap-2"><i className="ti ti-check text-accent mt-0.5"></i>Weekly progress reports</li>
            </ul>
            <Link to="/register" className="w-full block text-center bg-accent text-ink rounded-lg py-2 text-sm font-medium hover:bg-accent/90 transition">Get started</Link>
          </div>
          <div className="bg-panel border border-line rounded-xl p-6">
            <h3 className="font-display font-bold text-white mb-1">School</h3>
            <p className="font-display text-3xl font-bold text-white mb-4">Contact us</p>
            <ul className="text-sm text-muted space-y-2 mb-6">
              <li className="flex gap-2"><i className="ti ti-check text-accent mt-0.5"></i>Whole-cohort accounts</li>
              <li className="flex gap-2"><i className="ti ti-check text-accent mt-0.5"></i>Wellbeing &amp; engagement insights</li>
              <li className="flex gap-2"><i className="ti ti-check text-accent mt-0.5"></i>Assessment calendar import</li>
            </ul>
            <button className="w-full border border-line rounded-lg py-2 text-sm hover:border-accent/40 transition">Enquire</button>
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="border-t border-line">
        <div className="max-w-6xl mx-auto px-6 py-10 flex flex-col md:flex-row justify-between gap-6 text-sm text-muted">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="w-6 h-6 rounded-md bg-accent/15 border border-accent/30 flex items-center justify-center"><i className="ti ti-bolt text-accent text-xs"></i></span>
              <span className="font-display font-bold text-white">StudentSync</span>
            </div>
            <p>Built by a student, for students.</p>
          </div>
          <div className="flex gap-10">
            <div>
              <p className="text-white font-medium mb-2">Product</p>
              <Link to="/dashboard" className="block hover:text-white transition">Dashboard</Link>
              <Link to="/upload" className="block hover:text-white transition">Upload</Link>
              <Link to="/focus" className="block hover:text-white transition">Focus mode</Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}

function FeatureCard({ icon, title, desc }: { icon: string; title: string; desc: string }) {
  return (
    <div className="bg-panel border border-line rounded-xl p-5">
      <i className={`ti ${icon} text-accent text-2xl mb-4 block`}></i>
      <h3 className="font-display font-bold text-white mb-2">{title}</h3>
      <p className="text-sm text-muted">{desc}</p>
    </div>
  )
}
